### ISSUE TITLE
Getting Warning when running yarn dev

### ISSUE THREAD

**Issue by serge20** [williamluke4/Nitro#21]
When running the code with yarn dev a warning pops up.

in the cli:
```
Warning: Material-UI: you need to provide a sheetsManager to the StyleProvider when rendering on the server.
```

in the browser:
```
Warning: Failed prop type: The following properties are not supported: `registry`. Please remove them.
   in StylesProvider (at _app.tsx:36)
   in MyApp
```

**Comment by williamluke4** [comment]
@serge20 I'm currently waiting for MaterialUI v4.0.0 to drop before sorting this out :)

**Comment by williamluke4** [comment]
I will also likely be dropping styled components in favor of MUIs' style components like API

**Comment by williamluke4** [comment]
Should be fixed
